In [9]:
import torch
import torch.nn as nn

In [3]:
# TensorFlow
import tensorflow as tf
import torch

print("🔹 TensorFlow Tensors:")
tf_tensor = tf.constant([[1, 2], [3, 4]])
print("Tensor:\n", tf_tensor)
print("Shape:", tf_tensor.shape)
print("Data Type:", tf_tensor.dtype)

# PyTorch
print("\n🔸 PyTorch Tensors:")
torch_tensor = torch.tensor([[1, 2], [3, 4]])
print("Tensor:\n", torch_tensor)
print("Shape:", torch_tensor.shape)
print("Data Type:", torch_tensor.dtype)

🔹 TensorFlow Tensors:
Tensor:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Shape: (2, 2)
Data Type: <dtype: 'int32'>

🔸 PyTorch Tensors:
Tensor:
 tensor([[1, 2],
        [3, 4]])
Shape: torch.Size([2, 2])
Data Type: torch.int64


In [7]:
# Element-wise addition
print(tf_tensor + tf_tensor)
print(torch_tensor + torch_tensor)

# Matrix multiplication
print(tf.matmul(tf_tensor, tf_tensor))
print(torch.matmul(torch_tensor, torch_tensor))


tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)
tensor([[2, 4],
        [6, 8]])
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
tensor([[ 7, 10],
        [15, 22]])


In [8]:
tf_model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(10,)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1)  # Output layer
])

# Summary of model
tf_model.summary()

# Compile model (for training)
tf_model.compile(optimizer='adam', loss='mse')

c:\Users\manth\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,817 (11.00 KB)

 Trainable params: 2,817 (11.00 KB)

 Non-trainable params: 0 (0.00 B)

In [10]:
torch_model = nn.Sequential(
    nn.Linear(10, 64),
    nn.ReLU(),
    nn.Linear(64, 32),
    nn.ReLU(),
    nn.Linear(32, 1)
)

# Print model structure
print(torch_model)

# Example forward pass with random input
sample_input = torch.randn(5, 10)  # 5 samples, 10 features
output = torch_model(sample_input)
print("Output shape:", output.shape)

Sequential(
  (0): Linear(in_features=10, out_features=64, bias=True)
  (1): ReLU()
  (2): Linear(in_features=64, out_features=32, bias=True)
  (3): ReLU()
  (4): Linear(in_features=32, out_features=1, bias=True)
)
Output shape: torch.Size([5, 1])


In [11]:
# Sample data
x = tf.Variable([2.0, 3.0])

# Define a simple model (y = x^2)
with tf.GradientTape() as tape:
    y = x**2

# Calculate the gradient of y with respect to x
dy_dx = tape.gradient(y, x)
print("Gradients:", dy_dx)

Gradients: tf.Tensor([4. 6.], shape=(2,), dtype=float32)


In [12]:
x = tf.Variable([2.0, 3.0])
y_true = tf.Variable([4.0, 9.0])

# Simple linear model: y = w * x + b
w = tf.Variable(1.0)
b = tf.Variable(0.0)

# Learning rate
learning_rate = 0.01

# Training loop
for epoch in range(100):
    with tf.GradientTape() as tape:
        y_pred = w * x + b
        loss = tf.reduce_mean((y_true - y_pred)**2)  # Mean Squared Error
    gradients = tape.gradient(loss, [w, b])
    w.assign_sub(learning_rate * gradients[0])
    b.assign_sub(learning_rate * gradients[1])

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.numpy()}")

Epoch 0, Loss: 20.0
Epoch 10, Loss: 2.3589608669281006
Epoch 20, Loss: 1.6434338092803955
Epoch 30, Loss: 1.5946253538131714
Epoch 40, Loss: 1.5723425149917603
Epoch 50, Loss: 1.5513757467269897
Epoch 60, Loss: 1.5307279825210571
Epoch 70, Loss: 1.5103566646575928
Epoch 80, Loss: 1.490256667137146
Epoch 90, Loss: 1.4704233407974243


In [13]:
x = torch.tensor([2.0, 3.0], requires_grad=True)
y_true = torch.tensor([4.0, 9.0])

# Simple linear model: y = w * x + b
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

# Learning rate
learning_rate = 0.01

# Training loop
for epoch in range(100):
    y_pred = w * x + b
    loss = ((y_true - y_pred)**2).mean()  # Mean Squared Error
    loss.backward()  # Backpropagation

    with torch.no_grad():  # Update weights manually
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

        # Zero the gradients after each step
        w.grad.zero_()
        b.grad.zero_()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

Epoch 0, Loss: 20.0
Epoch 10, Loss: 2.3589608669281006
Epoch 20, Loss: 1.6434338092803955
Epoch 30, Loss: 1.5946253538131714
Epoch 40, Loss: 1.5723425149917603
Epoch 50, Loss: 1.5513757467269897
Epoch 60, Loss: 1.5307279825210571
Epoch 70, Loss: 1.5103566646575928
Epoch 80, Loss: 1.490256667137146
Epoch 90, Loss: 1.4704233407974243
